name: GitFlow Workflow

on:
  pull_request:
    types: [closed]
    branches: [develop, main]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop' && (startsWith(github.event.pull_request.head.ref, 'feat/') || startsWith(github.event.pull_request.head.ref, 'bugfix/')) || startsWith(github.event.pull_request.head.ref, 'refac/'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete merged feature/bugfix branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }} || echo "Branch already deleted or not found"

  sync-main-to-develop:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Git identity
        run: |
          git config user.name "SassyNic-git-flow[bot]"
          git config user.email "SassyNic@bot.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge release/ or hotfix/ into develop
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" == release/* || "${{ github.event.pull_request.head.ref }}" == hotfix/* ]]; then
            git checkout develop
            git merge origin/${{ github.event.pull_request.head.ref }} --no-ff --allow-unrelated-histories -m "chore(git-flow): merge ${{ github.event.pull_request.head.ref }} into develop [auto]"
            git push origin develop
          else
            git checkout develop
            git merge origin/main --no-ff --allow-unrelated-histories -m "chore(git-flow): sync main into develop [auto]"
            git push origin develop
          fi

      - name: Delete release/hotfix branch
        if: startsWith(github.event.pull_request.head.ref, 'release/') || startsWith(github.event.pull_request.head.ref, 'hotfix/')
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }} || echo "Branch already deleted or not found"
